version: "3.9"
services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: petclinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./external-services/data:/var/lib/postgres
      - ./external-services/init-db/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
      - ./external-services/init-db/populateDB.sql:/docker-entrypoint-initdb.d/populateDB.sql
  load-balancer:
    image: fabiolb/fabio
    ports:
      - "9999:9999"
      - "9998:9998"
    volumes:
      - ./external-services/fabio.properties:/etc/fabio/fabio.properties
